app:
  jwt:
    message: '"message"'
  jwtExpirationMs: 86400000
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetch-registry: true
  instance:
    preferIpAddress: true
    register-with-eureka: true
jwt:
  secret: bezKoderSecretKey
spring:
  application:
    name: eurekaclient
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Admin@123
    url: jdbc:mysql://localhost:3306/onehome
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
